ALTER TABLE Orders
ADD FullName NVARCHAR(255) NOT NULL DEFAULT 'Unknown';

ALTER TABLE Orders
ADD StreetAddress NVARCHAR(255) NOT NULL DEFAULT 'Unknown';

ALTER TABLE Orders
ADD AddressLine2 NVARCHAR(255) NULL;

ALTER TABLE Orders
ADD City NVARCHAR(100) NOT NULL DEFAULT 'Unknown';

ALTER TABLE Orders
ADD State NVARCHAR(100) NOT NULL DEFAULT 'Unknown';

ALTER TABLE Orders
ADD PostalCode NVARCHAR(20) NOT NULL DEFAULT '00000';

ALTER TABLE Orders
ADD Country NVARCHAR(100) NOT NULL DEFAULT 'Israel';
