UPDATE Books
SET Description = 
    CASE 
        WHEN Title = '1984' THEN 'George Orwell''s dystopian masterpiece, *1984*, immerses readers in a chilling world where the Party governs with absolute control. Citizens are under constant surveillance by Big Brother, and dissent is punished mercilessly. Winston Smith, the protagonist, begins to question the oppressive regime as he navigates a society where truth is manipulated, language is controlled, and individuality is erased. A haunting exploration of power, freedom, and resistance that continues to resonate in modern times.'

        WHEN Title = 'The Great Gatsby' THEN 'F. Scott Fitzgerald''s *The Great Gatsby* captures the dazzling highs and tragic lows of the American Dream during the Jazz Age. Set in 1920s Long Island, the novel follows the enigmatic Jay Gatsby, a wealthy man with an extravagant lifestyle and an unrelenting love for Daisy Buchanan. Narrated by Nick Carraway, the story explores themes of wealth, class division, love, and disillusionment in a society driven by materialism and excess.'

        WHEN Title = 'Harry Potter and the Sorcerers Stone' THEN 'J.K. Rowling''s *Harry Potter and the Sorcerer''s Stone* introduces readers to the magical world of Hogwarts School of Witchcraft and Wizardry. Orphaned and neglected, Harry Potter discovers on his eleventh birthday that he is a wizard and the Boy Who Lived. He embarks on a life-changing journey filled with new friendships, magical spells, and thrilling adventures. The book sets the stage for an epic battle between good and evil as Harry learns about his true heritage and faces dark forces.'

        WHEN Title = 'Cosmos' THEN 'In *Cosmos*, Carl Sagan takes readers on a mesmerizing journey through the universe, from the tiniest molecules to the farthest galaxies. Sagan beautifully blends science, history, and philosophy, exploring humanity''s place in the vast expanse of space. The book highlights our curiosity about the stars, the evolution of life, and the significance of scientific discovery. Written with poetic eloquence, *Cosmos* is a timeless celebration of knowledge and wonder.'

        WHEN Title = 'Me Before You' THEN 'Jojo Moyes'' *Me Before You* tells a poignant and unforgettable love story. Louisa Clark, a small-town girl with no clear direction in life, becomes a caregiver for Will Traynor, a once-successful man left paralyzed after an accident. As their lives intertwine, Louisa learns about courage, love, and the importance of living fully. Will''s struggle to accept his condition and Louisa''s determination to inspire him create a narrative that is both heartwarming and heartrending.'

        WHEN Title = 'Outlander' THEN 'Diana Gabaldon''s *Outlander* is an epic tale that blends historical fiction, romance, and time travel. Claire Randall, a former World War II nurse, is mysteriously transported back to 18th-century Scotland. There, she meets Jamie Fraser, a gallant Scottish warrior, and becomes entangled in a world of political intrigue, danger, and forbidden love. Through its rich storytelling and vivid descriptions, the book weaves together history and passion, captivating readers with its sweeping narrative.'

        WHEN Title = 'The Diary of a Young Girl' THEN 'Anne Frank''s *The Diary of a Young Girl* is an intimate and powerful account of her life during World War II. Written while she was in hiding with her family in Amsterdam, Anne''s diary captures the fears, hopes, and daily struggles of a young girl living under Nazi oppression. Despite the harsh reality of her situation, her words radiate resilience, optimism, and a deep love for life. This enduring memoir serves as a poignant reminder of the human cost of war and the enduring strength of the human spirit.'

        WHEN Title = 'Matilda' THEN 'Roald Dahl''s *Matilda* tells the story of an extraordinary little girl with a brilliant mind and an unshakable spirit. Born into a neglectful family, Matilda Wormwood finds solace in books and learning. She soon discovers she has a unique telekinetic power that helps her stand up to injustice, including her cruel school headmistress, Miss Trunchbull. This enchanting tale of courage, wit, and empowerment has delighted generations of readers and remains a timeless classic.'

        WHEN Title = 'Charlottes Web' THEN 'E.B. White''s *Charlotte''s Web* is a heartwarming story of friendship, compassion, and the power of selflessness. When Wilbur the pig learns he may soon face an unfortunate fate, his friend Charlotte, a wise and caring spider, devises a plan to save him. Through her remarkable web messages, Charlotte shows the world the beauty and worth of Wilbur. This beloved children''s classic is a touching reminder of the importance of kindness, loyalty, and sacrifice.'

        WHEN Title = 'Atomic Habits' THEN 'James Clear''s *Atomic Habits* provides a practical and powerful guide to building good habits, breaking bad ones, and mastering the tiny behaviors that lead to remarkable results. Through engaging anecdotes and actionable strategies, Clear demonstrates how small changes can compound into life-changing outcomes. With principles grounded in psychology and neuroscience, *Atomic Habits* empowers readers to take control of their behavior and unlock their potential.'

        WHEN Title = 'To Kill a Mockingbird' THEN 'Harper Lee''s *To Kill a Mockingbird* is a timeless exploration of racial injustice, morality, and compassion in the American South. Narrated by Scout Finch, the story follows her father, Atticus Finch, a lawyer who defends a Black man falsely accused of a crime. Through its powerful themes and unforgettable characters, the novel continues to inspire conversations about justice, equality, and humanity.'

        WHEN Title = 'Sapiens: A Brief History of Humankind' THEN 'Yuval Noah Harari''s *Sapiens* takes readers on an epic journey through human history, from the emergence of Homo sapiens to the present day. Harari explores how humans evolved, built civilizations, and shaped the world through culture, technology, and belief systems. Thought-provoking and insightful, *Sapiens* challenges readers to reflect on humanity''s past, present, and future.'

        WHEN Title = 'The Selfish Gene' THEN 'Richard Dawkins'' *The Selfish Gene* revolutionized our understanding of evolution and natural selection. Through the lens of the gene-centered view of evolution, Dawkins explores how genes drive behavior, survival, and reproduction. With clear explanations and fascinating examples, the book introduces readers to groundbreaking concepts such as memes, altruism, and selfishness in nature.'

        ELSE 'An amazing book with an engaging narrative, thoughtful themes, and profound lessons for readers to enjoy.'
    END;
